version: '3.8'

services:
  postgres:
    image: postgres:15.2-alpine
    container_name: postgres-chinook
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: chinook_serial
      POSTGRES_HOST_AUTH_METHOD: trust # 🔓 Никаких паролей, только доверие
      LANG: en_US.utf8
      LC_ALL: en_US.utf8
    volumes:
      - pg_data_chinook2:/var/lib/postgresql/data
      - ./Chinook_PostgreSql_SerialPKs.sql:/docker-entrypoint-initdb.d/init.sql
      # 🔥 Делаем данные доступными для записи с хоста
      - ./init_data_done:/init_data_done # Флаг, что инициализация прошла
    ports:
      - '25432:5432'
    networks:
      - superset_net
    restart: unless-stopped
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U admin -d chinook_serial']
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 10s

  superset:
    build: .
    container_name: superset-app
    depends_on:
      postgres:
        condition: service_healthy
    ports:
      - '8088:8088'
    environment:
      SUPERSET_SECRET_KEY: A0Zr98j/3yX R~XHH!jmN]LWX/,?RT
      DATABASE_URL: postgresql://admin:admin@postgres:5432/chinook_serial
      WTF_CSRF_ENABLED: 'False'
      FLASK_APP: superset.app:create_app
      PIP_ROOT_USER_ACTION: ignore
      SUPERSET_CONFIG_PATH: /app/superset_config.py
      # 🔥 Отключаем кэширование, включаем debug (опционально)
      FLASK_ENV: development
    volumes:
      # 🔥 Монтируем с полным доступом
      - ./superset_data:/app/superset_home:rw # superset.db, кэш, логи
      - ./superset_config.py:/app/superset_config.py:ro
      # 🔥 Гарантируем права на запись
      - ./chmod-fix.sh:/chmod-fix.sh
    networks:
      - superset_net
    healthcheck:
      test: ['CMD', 'curl', '-f', 'http://localhost:8088/health']
      interval: 10s
      timeout: 5s
      retries: 30
    command: >
      bash -c "
        # Запускаем fix-прав после старта
        chmod -R 777 /app/superset_home || true &&
        superset db upgrade &&
        superset fab create-admin --username admin --firstname Admin --lastname User --email admin@superset.com --password admin &&
        superset init &&
        # Ещё раз на всякий
        chmod -R 777 /app/superset_home || true &&
        superset run -h 0.0.0.0 -p 8088"

networks:
  superset_net:
    driver: bridge

volumes:
  pg_data_chinook2:
    driver: local
