version: '3.8'

services:
  postgres:
    image: postgres:15.2-alpine
    container_name: postgres-chinook
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_HOST_AUTH_METHOD: trust
      LANG: en_US.utf8
      LC_ALL: en_US.utf8
      POSTGRES_INITDB_ARGS: '--encoding=UTF8 --lc-collate=C --lc-ctype=C'
    volumes:
      - pg_data_chinook2:/var/lib/postgresql/data
      - ./Chinook_PostgreSql_SerialPKs.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - '25432:5432'
    networks:
      - superset_net
    restart: unless-stopped
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U admin -d chinook_serial']
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 10s

  superset:
    build: .
    container_name: superset-app
    depends_on:
      postgres:
        condition: service_healthy
    ports:
      - '8088:8088'
    environment:
      SUPERSET_SECRET_KEY: A0Zr98j/3yX R~XHH!jmN]LWX/,?RT
      DATABASE_URL: postgresql://admin:admin@postgres:5432/chinook_serial
      WTF_CSRF_ENABLED: 'False'
      FLASK_APP: superset.app:create_app
      PIP_ROOT_USER_ACTION: ignore
      # Указываем путь к кастомному конфигу
      SUPERSET_CONFIG_PATH: /app/superset_config.py
    volumes:
      # 🔥 Монтируем:
      - ./superset_data:/app/superset_home # Данные (superset.db)
      - ./superset_config.py:/app/superset_config.py # Конфигурация
    networks:
      - superset_net
    healthcheck:
      test: ['CMD', 'curl', '-f', 'http://localhost:8088/health']
      interval: 10s
      timeout: 5s
      retries: 30
    command: >
      bash -c "
        superset db upgrade &&
        superset fab create-admin --username admin --firstname Admin --lastname User --email admin@superset.com --password admin &&
        superset init &&
        superset run -h 0.0.0.0 -p 8088"

networks:
  superset_net:
    driver: bridge

volumes:
  pg_data_chinook2:
    driver: local
  # superset_data создаётся автоматически как папка на хосте (bind mount)
